language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive
    - git clone https://github.com/proycon/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
install: 
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
script: 
    - cd tests
    - ./testall
    
