sudo: required
dist: trusty
# whitelist
branches:
  only:
    - master

language: cpp
cache: ccache
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive autotools-dev ccache cppcheck clang libicu-dev libxml2-dev libbz2-dev zlib1g-dev libexttextcat-dev
    - export PATH="/usr/lib/ccache/bin/:$PATH"
    - cppcheck --enable=all --quiet --error-exitcode=2 .
    - git clone --depth=1 --single-branch https://github.com/proycon/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone --depth=1 --single-branch https://github.com/proycon/libfolia
    - cd libfolia
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone --depth=1 --single-branch https://github.com/LanguageMachines/uctodata
    - cd uctodata
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
install:
    - bash bootstrap.sh
    - scan-build --status-bugs ./configure
    - scan-build --status-bugs make
    - sudo make install
script:
    - cd tests && LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib ./testall >&2
after_failure:
    - tail -n 100 testoutput/*.diff
    - tail -n 100 testoutput/*.err
